### ISSUE TITLE
Error: wasm-bindgen v0.2.54 not installed!

### ISSUE THREAD

**Issue by mankinskin** [spielrs/yew-parcel-template#2]
I cloned this repository at 6dd839c791857ca425736c3950bb00e04adaf835 .
I installed parcel-bundler with `pacaur -S parcel-bundler` (version 1.12.4).
I ran
`cargo install wasm-pack --force` (installed version 0.8.1)
`npm run start`
<details>
<summary>Output</summary>
> create-yew-parcel@0.0.2 start /home/linusb/git/yew-parcel-template
> parcel index.html

Server running at http://localhost:1234
🚨  /home/linusb/git/yew-parcel-template/crate/Cargo.toml: Command failed: wasm-pack build -m no-install
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
 Downloading crates ...
  Downloaded dotenv v0.15.0
  Downloaded yew-router v0.7.0
  Downloaded yew v0.10.0
  Downloaded yew-router-macro v0.7.0
  Downloaded uuid v0.8.1
  Downloaded rmp-serde v0.13.7
  Downloaded anyhow v1.0.20
  Downloaded serde_yaml v0.8.11
  Downloaded yew-macro v0.10.0
  Downloaded wasm-bindgen-futures v0.4.4
  Downloaded rmp v0.8.8
  Downloaded yew-router-route-parser v0.7.0
  Downloaded serde_cbor v0.9.0
  Downloaded half v1.4.0
   Compiling proc-macro2 v1.0.6
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.7
   Compiling log v0.4.8
   Compiling cfg-if v0.1.10
   Compiling semver-parser v0.7.0
   Compiling ryu v1.0.0
   Compiling version_check v0.1.5
   Compiling serde v1.0.102
   Compiling memchr v2.2.1
   Compiling wasm-bindgen-shared v0.2.54
   Compiling lazy_static v1.4.0
   Compiling autocfg v0.1.7
   Compiling bumpalo v2.6.0
   Compiling arrayvec v0.4.12
   Compiling byteorder v1.3.2
   Compiling wasm-bindgen v0.2.54
   Compiling cc v1.0.46
   Compiling libc v0.2.65
   Compiling anyhow v1.0.20
   Compiling nodrop v0.1.14
   Compiling itoa v0.4.4
   Compiling failure_derive v0.1.6
   Compiling unicode-segmentation v1.3.0
   Compiling static_assertions v0.3.4
   Compiling stdweb-internal-runtime v0.1.5
   Compiling sha1 v0.6.0
   Compiling base-x v0.2.6
   Compiling rustc-demangle v0.1.16
   Compiling iovec v0.1.4
   Compiling proc-macro-nested v0.1.3
   Compiling linked-hash-map v0.5.2
   Compiling yew v0.10.0
   Compiling boolinator v2.4.0
   Compiling dtoa v0.4.4
   Compiling fnv v1.0.6
   Compiling sourcefile v0.1.4
   Compiling discard v1.0.4
   Compiling half v1.4.0
   Compiling anymap v0.12.1
   Compiling slab v0.4.2
   Compiling uuid v0.8.1
   Compiling dotenv v0.15.0
   Compiling semver v0.9.0
   Compiling nom v5.0.1
   Compiling nom v4.2.3
   Compiling num-traits v0.2.8
   Compiling indexmap v1.3.0
   Compiling yew-macro v0.10.0
   Compiling heck v0.3.1
   Compiling yaml-rust v0.4.3
   Compiling rustc_version v0.2.3
   Compiling quote v1.0.2
   Compiling bytes v0.4.12
   Compiling lexical-core v0.4.6
   Compiling stdweb v0.4.20
   Compiling http v0.1.19
   Compiling weedle v0.10.0
   Compiling rmp v0.8.8
   Compiling backtrace-sys v0.1.32
   Compiling backtrace v0.3.40
   Compiling wasm-bindgen-backend v0.2.54
   Compiling synstructure v0.12.1
   Compiling wasm-bindgen-macro-support v0.2.54
   Compiling wasm-bindgen-webidl v0.2.54
   Compiling yew-router-route-parser v0.7.0
   Compiling serde_derive v1.0.102
   Compiling wasm-bindgen-macro v0.2.54
   Compiling proc-macro-hack v0.5.11
   Compiling yew-router-macro v0.7.0
   Compiling web-sys v0.3.31
   Compiling js-sys v0.3.31
   Compiling failure v0.1.6
   Compiling wasm-bindgen-futures v0.4.4
   Compiling serde_json v1.0.41
   Compiling serde_cbor v0.9.0
   Compiling rmp-serde v0.13.7
   Compiling serde_yaml v0.8.11
   Compiling toml v0.4.10
   Compiling bincode v1.0.1
   Compiling stdweb-derive v0.5.3
   Compiling stdweb-internal-macros v0.2.9
   Compiling yew-router v0.7.0
   Compiling yew-parcel v0.1.0 (/home/linusb/git/yew-parcel-template/crate)
    Finished release [optimized] target(s) in 2m 50s
:-) [WARN]: origin crate has no README
[INFO]: License key is set in Cargo.toml but no LICENSE file(s) were found; Please add the LICENSE file(s) to your project directory
[INFO]: Installing wasm-bindgen...
Error: wasm-bindgen v0.2.54 is not installed!

[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
 Downloading crates ...
  Downloaded dotenv v0.15.0
  Downloaded yew-router v0.7.0
  Downloaded yew v0.10.0
  Downloaded yew-router-macro v0.7.0
  Downloaded uuid v0.8.1
  Downloaded rmp-serde v0.13.7
  Downloaded anyhow v1.0.20
  Downloaded serde_yaml v0.8.11
  Downloaded yew-macro v0.10.0
  Downloaded wasm-bindgen-futures v0.4.4
  Downloaded rmp v0.8.8
  Downloaded yew-router-route-parser v0.7.0
  Downloaded serde_cbor v0.9.0
  Downloaded half v1.4.0
   Compiling proc-macro2 v1.0.6
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.7
   Compiling log v0.4.8
   Compiling cfg-if v0.1.10
   Compiling semver-parser v0.7.0
   Compiling ryu v1.0.0
   Compiling version_check v0.1.5
   Compiling serde v1.0.102
   Compiling memchr v2.2.1
   Compiling wasm-bindgen-shared v0.2.54
   Compiling lazy_static v1.4.0
   Compiling autocfg v0.1.7
   Compiling bumpalo v2.6.0
   Compiling arrayvec v0.4.12
   Compiling byteorder v1.3.2
   Compiling wasm-bindgen v0.2.54
   Compiling cc v1.0.46
   Compiling libc v0.2.65
   Compiling anyhow v1.0.20
   Compiling nodrop v0.1.14
   Compiling itoa v0.4.4
   Compiling failure_derive v0.1.6
   Compiling unicode-segmentation v1.3.0
   Compiling static_assertions v0.3.4
   Compiling stdweb-internal-runtime v0.1.5
   Compiling sha1 v0.6.0
   Compiling base-x v0.2.6
   Compiling rustc-demangle v0.1.16
   Compiling iovec v0.1.4
   Compiling proc-macro-nested v0.1.3
   Compiling linked-hash-map v0.5.2
   Compiling yew v0.10.0
   Compiling boolinator v2.4.0
   Compiling dtoa v0.4.4
   Compiling fnv v1.0.6
   Compiling sourcefile v0.1.4
   Compiling discard v1.0.4
   Compiling half v1.4.0
   Compiling anymap v0.12.1
   Compiling slab v0.4.2
   Compiling uuid v0.8.1
   Compiling dotenv v0.15.0
   Compiling semver v0.9.0
   Compiling nom v5.0.1
   Compiling nom v4.2.3
   Compiling num-traits v0.2.8
   Compiling indexmap v1.3.0
   Compiling yew-macro v0.10.0
   Compiling heck v0.3.1
   Compiling yaml-rust v0.4.3
   Compiling rustc_version v0.2.3
   Compiling quote v1.0.2
   Compiling bytes v0.4.12
   Compiling lexical-core v0.4.6
   Compiling stdweb v0.4.20
   Compiling http v0.1.19
   Compiling weedle v0.10.0
   Compiling rmp v0.8.8
   Compiling backtrace-sys v0.1.32
   Compiling backtrace v0.3.40
   Compiling wasm-bindgen-backend v0.2.54
   Compiling synstructure v0.12.1
   Compiling wasm-bindgen-macro-support v0.2.54
   Compiling wasm-bindgen-webidl v0.2.54
   Compiling yew-router-route-parser v0.7.0
   Compiling serde_derive v1.0.102
   Compiling wasm-bindgen-macro v0.2.54
   Compiling proc-macro-hack v0.5.11
   Compiling yew-router-macro v0.7.0
   Compiling web-sys v0.3.31
   Compiling js-sys v0.3.31
   Compiling failure v0.1.6
   Compiling wasm-bindgen-futures v0.4.4
   Compiling serde_json v1.0.41
   Compiling serde_cbor v0.9.0
   Compiling rmp-serde v0.13.7
   Compiling serde_yaml v0.8.11
   Compiling toml v0.4.10
   Compiling bincode v1.0.1
   Compiling stdweb-derive v0.5.3
   Compiling stdweb-internal-macros v0.2.9
   Compiling yew-router v0.7.0
   Compiling yew-parcel v0.1.0 (/home/linusb/git/yew-parcel-template/crate)
    Finished release [optimized] target(s) in 2m 50s
:-) [WARN]: origin crate has no README
[INFO]: License key is set in Cargo.toml but no LICENSE file(s) were found; Please add the LICENSE file(s) to your project directory
[INFO]: Installing wasm-bindgen...
Error: wasm-bindgen v0.2.54 is not installed!

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
</details>

**Comment by mankinskin** [comment]
```
cd crate/
cargo update
wasm-pack build -m no-install
cd ..
npm run start
```
Fixes this. Probably should use `wasm-pack build` without `-m no-install` in the build scripts...

**Comment by spielcrypto** [comment]
Sorry I was not available. I have to check it and surely update the dependencies

**Comment by spielcrypto** [comment]
I updated yew and yew-router versions and I tested. You shouldn't have any problem now anyway feel free to open the ticket in case that you have.
