### ISSUE TITLE
Build target should be specified in .cargo/config

### ISSUE THREAD

**Issue by vaffeine** [spielrs/yew-parcel-template#5]
Hi. Thank you for a nice template.

However, I noticed a small issue with it. `build.target key` is specified in `Cargo.toml`, when it should be placed in `.cargo/config` file, as described in MR that added it - https://github.com/rust-lang/cargo/pull/2335.

Cargo ignores `build.target` in Cargo.toml and produces a warning "warning: unused manifest key: build".

`.cargo/config` can be created per project, as described at https://doc.rust-lang.org/cargo/reference/config.html. Everything seems to work when I move `build.target` from `crate/Cargo.toml` to `crate/.cargo/config`.

I can submit an MR to fix that, if you want.

**Comment by spielcrypto** [comment]
You are right, it is something that I was changing in another projects. I will fix it, thanks a lot!

**Comment by spielcrypto** [comment]
I think with this [commit](https://github.com/spielrs/yew-parcel-template/commit/e6655b50bf5893815a64455a453d613f1050e907) I fixed this issue. If it is not like this please feel free to open the issue again

**Comment by vaffeine** [comment]
Yes, that is what I meant. Thank you
